name: On push

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - run: echo Checkout done for $GITHUB_REF
      - name: condiational
        run: echo Only for tags 
        if: ${{ contains(github.ref, 'tag') }}
