name: On push

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - run: echo Checkout done for $GITHUB_REF
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/releases/v') }}
    needs: validate
    runs-on: "ubuntu-latest"
    steps:
      - name: Get release number
        run: echo "::set-output name=release_number::echo $GITHUB_REF | sed -n -e 's/^refs\/tags\/releases\/\(v.*\)/\1/p'"
      - name: Release
        run: echo Only for releases tags  ${{steps.release.outputs.release_number}} 
