name: On push

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - run: echo Checkout done for $GITHUB_REF
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/releases/v') }}
    needs: validate
    runs-on: "ubuntu-latest"
    steps:
      - name: Release
        run: echo Only for releases tags
